---
- name: Pi Ansible Setup
  hosts: pi
  vars:
    domain: kekskurse.ddns.net
    mail: pi@kekskurse.de
  roles:
    - common
    - mqtt
  tasks:
    - name: Create the User soeren
      user:
        name: soeren
        shell: /bin/zsh
        append: yes
      become: yes
    - name: Set authorized keys taken from url
      authorized_key:
        user: soeren
        state: present
        key: https://github.com/sspssp.keys
      become: yes
    - name: Download grml config
      get_url:
        url: https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
        dest: /home/soeren/.zshrc
        mode: 0660
        owner: soeren
        group: soeren
      become: true
